### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by MaksM181** [jakucermak/BLuetoothHID#1]
Traceback (most recent call last):
  File "btk_server.py", line 320, in <module>
    myservice = BTKbService()
  File "btk_server.py", line 295, in __init__
    self.device.listen()
  File "btk_server.py", line 238, in listen
    self.scontrol.bind((self.address, self.P_CTRL))
OSError: [Errno 98] Address already in use

**Comment by jakucermak** [comment]
Hello, can you describe more. Such as hw or process how you are attempt to run server.

**Comment by jakucermak** [comment]
I did some investigation and this worked for me:

First you need to stop bluetooth service: ` sudo service bluetooth stop `.
Then you need to start bluetooth daemon with input parameter in my case located in libexec folder, but could be in lib folder: ` sudo /usr/libexec/bluetooth/bluetoothd -P input `
