### ISSUE TITLE
Some restart problems

### ISSUE THREAD

**Issue by Chino-Kafuu-tyan** [jakucermak/BLuetoothHID#2]
I want to use part of this program for my project (emulation of pressing the Enter key to take photos from the phone). However, I have a few problems.
1. If my device is disconnected or I have stopped the server, or if the device was already connected before starting, my connections no longer work (constant waiting for connection)
2. My Pi does not have a keyboard, I communicate with it via VNC Server. Can the program work without a keyboard connected and/or with a prescribed script?

**Comment by jakucermak** [comment]
1. At this point reconnect is not implemented, needs to be done manually. Disconnect from device using bluetoothctl or on physical device. This feature going to be implemented in future
2. project listens for events from physical device using evdev, but realVNC does not. There is option to change 
```
if __name__ == '__main__':
    print('Setting up keyboard')
    kb = Kbrd()

    print('starting event loop')
    kb.event_loop()
```
to
```
if __name__ == '__main__':
    print('Setting up keyboard')
    kb = Kbrd()

    print('starting event loop')
    kb.event_loop_term()
```
it uses sshkeyboard package, but special keys are not implemented, so you need to remap your project to different key, and connect to pi over ssh.
